"""added field user_uid in images

Revision ID: 31871ce0b3bd
Revises: b85d14733f78
Create Date: 2026-05-30 00:32:29.155907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31871ce0b3bd'
down_revision: Union[str, Sequence[str], None] = 'b85d14733f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_uid', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'user_uid')
    # ### end Alembic commands ###
