"""added field iv and mime_type in image model

Revision ID: 4aa354d83840
Revises: da7a27c15a07
Create Date: 2026-05-29 17:24:06.009226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa354d83840'
down_revision: Union[str, Sequence[str], None] = 'da7a27c15a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('iv', sa.String(), nullable=False))
    op.add_column('images', sa.Column('mime_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'mime_type')
    op.drop_column('images', 'iv')
    # ### end Alembic commands ###
