"""added field public_id

Revision ID: b85d14733f78
Revises: 4aa354d83840
Create Date: 2026-05-30 00:09:37.115926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85d14733f78'
down_revision: Union[str, Sequence[str], None] = '4aa354d83840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('public_id', sa.String(), nullable=False))
    op.add_column('images', sa.Column('original_name', sa.String(), nullable=False))
    op.add_column('images', sa.Column('size', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'size')
    op.drop_column('images', 'original_name')
    op.drop_column('images', 'public_id')
    # ### end Alembic commands ###
