"""added field name uploaded_at in images table

Revision ID: da7a27c15a07
Revises: d09f9f8b28f3
Create Date: 2026-05-25 17:09:09.361935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7a27c15a07'
down_revision: Union[str, Sequence[str], None] = 'd09f9f8b28f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'uploaded_at')
    # ### end Alembic commands ###
